### ISSUE TITLE
Invalid sequence errors

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-contracts.js#8] opened 2015-08-10 03:43 UTC
This tends to happen if I overload erisdb with a lot of transactions at once. The problem is that it seems to persist into future transactions. I can only get it to go away by resetting the chain

```
[JSON RPC 2.0 Error] Message Id: 95, (INTERNAL_ERROR) - Error broadcasting transaction: Error invalid sequence. Got 67, expected 68
[Error: Error broadcasting transaction: Error invalid sequence. Got 67, expected 68]
Error callback from sendTransaction
[JSON RPC 2.0 Error] Message Id: 113, (INTERNAL_ERROR) - Error broadcasting transaction: Error invalid sequence. Got 67, expected 68
[Error: Error broadcasting transaction: Error invalid sequence. Got 67, expected 68]
Error callback from sendTransaction
[JSON RPC 2.0 Error] Message Id: 93, (INTERNAL_ERROR) - Error broadcasting transaction: Error invalid sequence. Got 67, expected 68
[Error: Error broadcasting transaction: Error invalid sequence. Got 67, expected 68]
Error callback from sendTransaction
[JSON RPC 2.0 Error] Message Id: 92, (INTERNAL_ERROR) - Error broadcasting transaction: Error invalid sequence. Got 67, expected 68
[Error: Error broadcasting transaction: Error invalid sequence. Got 67, expected 68]
Error callback from sendTransaction
[JSON RPC 2.0 Error] Message Id: 105, (INTERNAL_ERROR) - Error broadcasting transaction: Error invalid sequence. Got 67, expected 68
[Error: Error broadcasting transaction: Error invalid sequence. Got 67, expected 68]
Error callback from sendTransaction
```

**Comment by dennismckinnon** [comment] 2015-08-10 03:48
I should note that this error seems *mostly* superficial. If erisdb doesn't crash the transactions are still carried out. However the callbacks for the transactions seem to be triggered before the completion of the transaction itself without a passed error. (resulting in false successes in my case)

**Comment by androlo** [comment] 2015-08-10 08:58
Sorry this will take a little while to bone out. It looks like it might be a combination of different errors. I'll get back to this later today.

**Comment by androlo** [comment] 2015-08-11 12:17
from what i've heard, you're passing transactions to some sort of relaying service that passes the transactions on to different eris-db nodes. That would cause nonce errors since they each take the current nonce from their local database. in that case it's not a bug.

this is still an issue though (a general, tendermint one), which we're gonna have to get into fairly soon: when rpc-ing, where will nonce update be done, how will it work etc. all solutions will probably have pros and cons.

leaving this here.

**Comment by dennismckinnon** [comment] 2015-08-11 12:41
No this wasnt caused by that. These occur when a large number of transactions get sent simutaneously. Ethan suspects that the nonce that is fetched doesnt get updated until the transaction is processed. We might need to track the nonce client side.

**Comment by androlo** [comment] 2015-08-11 13:10
weird, i send 100+ txs at the same time here: https://github.com/eris-ltd/eris-contracts.js/tree/master/test/live/create_and_transact_x100

it's commented out because i dont want it auto running with the live tests, but it's been working reliably for me.

**Comment by dennismckinnon** [comment] 2015-08-11 13:13
You are using a for loop there which is not asynchronous. It will wait for one transaction to finish before doing the next. Try using async.each there instead.

**Comment by dennismckinnon** [comment] 2015-08-11 13:15
You are using a for loop there. Maybe try using async.each instead and see if it still works.

**Comment by androlo** [comment] 2015-08-11 13:18
isn't the issue that you can't run them all at once?

"These occur when a large number of transactions get sent simutaneously. "

**Comment by androlo** [comment] 2015-08-11 13:19
weird. so i have to send a tx, wait for the tx return (but not the block mined) before i send the next?

**Comment by dennismckinnon** [comment] 2015-08-11 13:23
Honestly not entirely sure what is going on here. I just know that both times I have gotten this error has been at the same time as a bunch of transactions are being sent in async.each

which doesn't wait for the transaction to complete but it will wait until all the callbacks from each transaction has been called.

If I have time after working through the other issue I'll try to find you a replicable example of it occurring.

**Comment by androlo** [comment] 2015-08-11 13:27
no that's great. that is a use-case i haven't tested. i only plow them all in at once. not one after the other. i'll test it.

**Comment by androlo** [comment] 2015-08-11 13:36
well, actually i have, but not with a large number of txs at once.

**Comment by androlo** [comment] 2015-08-28 02:48
tendermint/eris-db issues. will be solved when eris-db is updated and latest tendermint is pulled in. closing.

**Closed by androlo** 2015-08-28 02:48 UTC
Labels: help wanted
